'use strict';

/**
 * Sequelize Model Loader
 *
 * This file is auto-generated by Sequelize CLI and acts as a central loader
 * for all model definitions in the models/ directory.
 *
 * It performs three main tasks when the application starts:
 * 1. Imports every model file in the folder
 * 2. Registers each model with Sequelize
 * 3. Executes each model's associate() function to establish relationships
 *
 * Example loading flow:
 *
 * models/
 *   index.js
 *   user.js
 *   application.js
 *   contact.js
 *   activity.js
 *   task.js
 *
 * When the server runs, this file automatically loads each model and then
 * connects them together by executing their defined associations.
 */

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const process = require('process');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/config.json')[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs.readdirSync(__dirname)
  .filter((file) => {
    return (
      file.indexOf('.') !== 0 &&
      file !== basename &&
      file.slice(-3) === '.js' &&
      file.indexOf('.test.js') === -1
    );
  })
  .forEach((file) => {
    const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
    db[model.name] = model;
  });

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
